#!/bin/sh

cd ~/vlmcsd/hotbird64-mass-build

export VLMCSD_VERSION=$(git describe)

BINDIR="bin"
cd ..

# Compile vlmcsd binaries for Minix 3

SUFFIX=-minix-$(uname -r)-x86
export CC=clang
export CFLAGS="-pipe -fno-common -fno-exceptions -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fmerge-all-constants"
export LDFLAGS="-Wl,--hash-style=sysv -Wl,-z,norelro -Wl,--build-id=none"
export PROGRAM_NAME=$BINDIR/vlmcsd$SUFFIX
export CLIENT_NAME=$BINDIR/vlmcs$SUFFIX
export MULTI_NAME=$BINDIR/vlmcsdmulti$SUFFIX

gmake clean
gmake -B allmulti

#strip -s --strip-unneeded --remove-section .eh_frame_hdr --remove-section .eh_frame --remove-section .ident --remove-section .note.minix.ident --remove-section .note.netbsd.pax --remove-section=.note.gnu.gold-version --remove-section=.comment --remove-section=.note --remove-section=.note.gnu.build-id --remove-section=.note.ABI-tag $BINDIR/*$SUFFIX

scp -p $BINDIR/* root@ubuntu64.internal:x/binaries/Minix/intel/
